##### nginx ENV install
FROM nginx:latest
RUN rm -rf /etc/nginx/conf.d/default.d
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
